[options]

; Master password for database operations
admin_passwd = shuuri^oodo@db

; Database
db_host = db
db_port = 5432
db_user = odoo
db_password = shuuri^oodo@postgres

; Addons
addons_path = /mnt/extra-addons/custom,/mnt/extra-addons/third_party,/usr/lib/python3/dist-packages/odoo/addons

; Data directory
data_dir = /var/lib/odoo

; Logging
log_level = debug
logfile = False

; Development
proxy_mode = False

; Database filtering
dbfilter = ^odoo18_dev$